"use strict";
exports.__esModule = true;
var Matrix_1 = require("./Matrix");
var example = new Matrix_1.Matrix(2, 2);
example.addTenant(null, "1");
example.addTenant(null, "2");
example.addTenant(null, "3");
example.addTenant(null, "4");
example.addTenant(null, "5");
example.addTenant(null, "6");
console.log(example);
